import React, { useEffect, useState } from "react";
import { CheckCircle2, CircleDollarSign, Edit3, Plus, RefreshCw, ShieldCheck, Wallet, XCircle } from "lucide-react";
import { resolveApiUrl } from "../lib/apiClient";

const money=(n:number)=>`$${Number(n||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`;
export function AdminRevenueShareTab({ adminEmail, onToast }: { adminEmail: string; onToast: (msg:string)=>void }) {
  const [data,setData]=useState<any>({plans:[],investments:[],withdrawals:[],revenuePools:[],metrics:{}}); const [loading,setLoading]=useState(true);
  const [plan,setPlan]=useState<any>({name:"",minDeposit:"",maxDeposit:"",revenueSharePercent:"",payoutCycle:"Monthly",coinConversionRate:"100",status:"Active"});
  const [pool,setPool]=useState({month:new Date().toISOString().slice(0,7),amount:""});
  const [investorSearch,setInvestorSearch]=useState("");
  const [investorFilter,setInvestorFilter]=useState("All");
  const load=async()=>{setLoading(true);try{const r=await fetch(`${resolveApiUrl("/api/v1/admin/revenue-share")}`,{headers:{"Content-Type":"application/json","x-admin-email":adminEmail},cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to load Revenue Share admin data.");setData(d);}catch(e:any){onToast(e.message||"Revenue Share load failed.");}finally{setLoading(false);}};
  useEffect(()=>{void load();},[adminEmail]);
  const call=async(url:string,method:string,body:any)=>{const r=await fetch(resolveApiUrl(url),{method,headers:{"Content-Type":"application/json","x-admin-email":adminEmail},body:JSON.stringify({...body,adminEmail})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Request failed");return d;};
  const createPlan=async()=>{try{await call("/api/v1/admin/revenue-share/plans","POST",{...plan,minDeposit:Number(plan.minDeposit),maxDeposit:plan.maxDeposit===""?null:Number(plan.maxDeposit),revenueSharePercent:Number(plan.revenueSharePercent),coinConversionRate:Number(plan.coinConversionRate)});setPlan({name:"",minDeposit:"",maxDeposit:"",revenueSharePercent:"",payoutCycle:"Monthly",coinConversionRate:"100",status:"Active"});onToast("Revenue Share plan created.");await load();}catch(e:any){onToast(e.message);}};
  const setPlanStatus=async(p:any)=>{try{await call(`/api/v1/admin/revenue-share/plans/${p.id}`,"PUT",{status:p.status==="Active"?"Inactive":"Active"});onToast(`${p.name} ${p.status==="Active"?"disabled":"enabled"}.`);await load();}catch(e:any){onToast(e.message);}};
  const approveInvestment=async(i:any,status:string)=>{try{await call(`/api/v1/admin/revenue-share/investments/${i.id}/status`,"POST",{status});onToast(`${i.id}: ${status}`);await load();}catch(e:any){onToast(e.message);}};
  const createPool=async()=>{try{await call("/api/v1/admin/revenue-share/pools","POST",{month:pool.month,amount:Number(pool.amount)});onToast("Revenue pool created.");setPool({...pool,amount:""});await load();}catch(e:any){onToast(e.message);}};
  const poolAction=async(p:any,status:string)=>{try{await call(`/api/v1/admin/revenue-share/pools/${p.id}/${status==="Distributed"?"distribute":"status"}`,"POST",status==="Distributed"?{}:{status});onToast(`${p.id}: ${status}`);await load();}catch(e:any){onToast(e.message);}};
  const withdrawalAction=async(w:any,status:string)=>{try{await call(`/api/v1/admin/revenue-share/withdrawals/${w.id}/status`,"POST",{status});onToast(`${w.id}: ${status}`);await load();}catch(e:any){onToast(e.message);}};
  if(loading)return <div className="p-6 text-xs text-cyan-300 font-mono">Loading Revenue Share Management…</div>;
  const m=data.metrics||{};
  return <div className="space-y-5">
    <div className="flex items-center justify-between"><div><h2 className="text-xl font-black text-white">Revenue Share Management</h2><p className="text-[9px] text-gray-500">Isolated investment, earnings and distribution controls.</p></div><button onClick={()=>void load()} className="p-2 rounded-xl border border-white/10 text-gray-300"><RefreshCw className="w-4 h-4"/></button></div>
    <div className="grid grid-cols-2 md:grid-cols-4 gap-2">{[["Investors",m.totalInvestors],["Active Investments",m.activeInvestments],["Total Deposits",money(m.totalDeposits)],["Earnings Distributed",money(m.totalEarningsDistributed)],["Pending Deposits",m.pendingDeposits],["Pending Withdrawals",m.pendingWithdrawals],["Active Principal",money(m.totalPrincipal)],["Approved Pool",money(m.revenuePool)]].map(([k,v])=><div key={String(k)} className="rounded-2xl border border-white/10 bg-[#11111b] p-3"><p className="text-[7px] text-gray-500 uppercase font-black">{k}</p><p className="text-base font-black text-white mt-1">{v}</p></div>)}</div>
    <div className="rounded-2xl border border-white/10 bg-[#11111b] p-4"><h3 className="text-sm font-black text-white flex items-center gap-2"><CircleDollarSign className="w-4 h-4 text-yellow-300"/> Plan Management</h3><div className="grid grid-cols-2 md:grid-cols-4 gap-2 mt-3">{Object.entries({name:"Plan name",minDeposit:"Min",maxDeposit:"Max",revenueSharePercent:"Share %",coinConversionRate:"Coins / $",payoutCycle:"Cycle"}).map(([k,label])=><input key={k} value={plan[k]} onChange={e=>setPlan({...plan,[k]:e.target.value})} placeholder={label} className="bg-black/30 border border-white/10 rounded-xl px-2.5 py-2 text-[9px] text-white"/>)}<select value={plan.status} onChange={e=>setPlan({...plan,status:e.target.value})} className="bg-black/30 border border-white/10 rounded-xl px-2.5 py-2 text-[9px] text-white"><option>Active</option><option>Inactive</option></select><button onClick={()=>void createPlan()} className="rounded-xl bg-gradient-to-r from-pink-500 to-purple-600 text-white text-[9px] font-black"><Plus className="w-3.5 h-3.5 inline mr-1"/>Create Plan</button></div><div className="grid md:grid-cols-2 gap-2 mt-4">{data.plans.map((p:any)=><div key={p.id} className="rounded-xl border border-white/10 p-3 bg-white/[0.02] flex items-center justify-between"><div><p className="text-[10px] font-black text-white">{p.name}</p><p className="text-[8px] text-gray-500">{money(p.minDeposit)}{p.maxDeposit?` – ${money(p.maxDeposit)}`:"+"} · {p.revenueSharePercent}% · {p.coinConversionRate} coins/$</p></div><button onClick={()=>void setPlanStatus(p)} className={`text-[8px] font-black border rounded-full px-2 py-1 ${p.status==="Active"?"text-emerald-300 border-emerald-400/20":"text-gray-400 border-white/10"}`}>{p.status}</button></div>)}</div></div>
    <div className="rounded-2xl border border-white/10 bg-[#11111b] p-4"><h3 className="text-sm font-black text-white">Investor Management</h3><div className="flex gap-2 mt-3"><input value={investorSearch} onChange={e=>setInvestorSearch(e.target.value)} placeholder="Search username / Investment ID" className="flex-1 bg-black/30 border border-white/10 rounded-xl px-3 py-2 text-[9px] text-white"/><select value={investorFilter} onChange={e=>setInvestorFilter(e.target.value)} className="bg-black/30 border border-white/10 rounded-xl px-2 text-[9px] text-white"><option>All</option><option>Active</option><option>Pending</option><option>Suspended</option><option>Rejected</option></select></div><div className="mt-3 space-y-1.5">{data.investments.filter((i:any)=>(investorFilter==="All"||i.status===investorFilter)&&((String(i.username||"")+" "+String(i.id||"")).toLowerCase().includes(investorSearch.toLowerCase()))).slice(0,30).map((i:any)=><div key={i.id} className="rounded-xl bg-white/[0.03] border border-white/5 p-2.5 flex items-center justify-between"><div><p className="text-[9px] font-black text-white">@{i.username} · {i.id}</p><p className="text-[8px] text-gray-500">{i.planName} · Principal {money(i.principal)} · Earned {money(i.totalEarnings||0)}</p></div><span className={`text-[7px] border rounded-full px-2 py-1 ${i.status==="Active"?"text-emerald-300 border-emerald-400/20":"text-amber-300 border-amber-400/20"}`}>{i.status}</span></div>)}</div></div>

    <div className="rounded-2xl border border-white/10 bg-[#11111b] p-4"><h3 className="text-sm font-black text-white">Pending Investments</h3>{data.investments.filter((i:any)=>i.status==="Pending").map((i:any)=><div key={i.id} className="flex items-center justify-between gap-2 border-b border-white/5 py-3"><div><p className="text-[9px] font-black text-white">{i.id} · @{i.username}</p><p className="text-[8px] text-gray-500">{i.planName} · {money(i.principal)} · {i.paymentMethod}</p></div><div className="flex gap-1"><button onClick={()=>void approveInvestment(i,"Active")} className="px-2 py-1 rounded-lg bg-emerald-500/15 text-emerald-300 text-[8px] font-black">Approve</button><button onClick={()=>void approveInvestment(i,"Rejected")} className="px-2 py-1 rounded-lg bg-red-500/15 text-red-300 text-[8px] font-black">Reject</button></div></div>)}</div>
    <div className="rounded-2xl border border-white/10 bg-[#11111b] p-4"><h3 className="text-sm font-black text-white">Monthly Revenue Pool</h3><div className="flex gap-2 mt-3"><input type="month" value={pool.month} onChange={e=>setPool({...pool,month:e.target.value})} className="bg-black/30 border border-white/10 rounded-xl px-2 text-[9px] text-white"/><input type="number" value={pool.amount} onChange={e=>setPool({...pool,amount:e.target.value})} placeholder="Revenue amount" className="flex-1 bg-black/30 border border-white/10 rounded-xl px-2 text-[9px] text-white"/><button onClick={()=>void createPool()} className="px-3 rounded-xl bg-yellow-400 text-black text-[9px] font-black">Create Pool</button></div>{data.revenuePools.map((p:any)=><div key={p.id} className="mt-2 flex items-center justify-between border-b border-white/5 py-2"><span className="text-[8px] text-white">{p.month} · {money(p.amount)} · {p.status}</span><div className="flex gap-1">{p.status==="Draft"&&<button onClick={()=>void poolAction(p,"Approved")} className="text-[8px] text-emerald-300">Approve</button>}{p.status==="Approved"&&<button onClick={()=>void poolAction(p,"Distributed")} className="text-[8px] text-pink-300">Distribute</button>}</div></div>)}</div>
    <div className="rounded-2xl border border-white/10 bg-[#11111b] p-4"><h3 className="text-sm font-black text-white flex items-center gap-2"><Wallet className="w-4 h-4 text-cyan-300"/> Withdrawal Queue</h3>{data.withdrawals.filter((w:any)=>w.status==="Pending").map((w:any)=><div key={w.id} className="flex items-center justify-between border-b border-white/5 py-3"><div><p className="text-[9px] font-black text-white">{w.id} · @{w.username}</p><p className="text-[8px] text-gray-500">{w.type} · {money(w.amount)} · {w.payoutFormat}</p></div><div className="flex gap-1"><button onClick={()=>void withdrawalAction(w,"Approved")} className="text-[8px] text-emerald-300">Approve</button><button onClick={()=>void withdrawalAction(w,"Rejected")} className="text-[8px] text-red-300">Reject</button></div></div>)}</div>
  </div>;
}
